# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks
repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.3.0
    hooks:
    -   id: trailing-whitespace
    -   id: end-of-file-fixer
    -   id: check-yaml
    -   id: check-added-large-files
-   repo: https://github.com/jorisroovers/gitlint
    rev: v0.17.0
    hooks:
    -   id: gitlint
-   repo: https://github.com/jackdewinter/pymarkdown
    rev: v0.9.8
    hooks:
    -   id: pymarkdown
-   repo: https://github.com/ambv/black
    rev: 22.10.0
    hooks:
    -   id: black
        language_version: python3.7
