filter:
  paths: ["adminAPI/*", "userAPI/*", "react/*", "customerapp/*"]

checks:
  javascript:
    no_var: true
    eqeqeq: true
    no_else_return: true
    no_alert: true

build:
  nodes:
    analysis:
      tests:
        override:
          - js-scrutinizer-run
    tests: true
