version: "3.4"

services:

   admin-api:
     container_name: admin-api
     build: ./adminAPI
     working_dir: /code
     command: npm run start:dev
     volumes:
       - ./adminAPI/app:/code/app
     ports:
       - 8081:3000
     restart: on-failure

   user-api:
     container_name: user-api
     build: ./userAPI
     working_dir: /code
     command: npm run start:dev
     volumes:
       - ./userAPI/app:/code/app
     ports:
       - 8082:3000
     restart: on-failure

   react:
     container_name: react
     build: ./react
     working_dir: /code/src
     command: npm start
     volumes:
       - ./react/src:/code/src
     ports:
       - 8083:3001
     restart: on-failure

   mariadb:
     container_name: mariadb
     image: mariadb:latest
     restart: always
     volumes:
      - ./mariadb/:/docker-entrypoint-initdb.d/
     ports:
       - 8084:3306
     environment:
       MYSQL_ROOT_PASSWORD: admin
       MYSQL_DATABASE: mydb
       MYSQL_USER: user
       MYSQL_PASSWORD: user
