version: "3.4"

services:

   express:
     container_name: express
     build: ./express
     working_dir: /code
     command: npm run start:dev
     volumes:
       - ./express/app:/code/app
     ports:
       - 8081:3000
     restart: on-failure

   react:
     container_name: react
     build: ./react
     working_dir: /code/src
     command: npm start
     volumes:
       - ./react/src:/code/src
     ports:
       - 3000:3000
     restart: on-failure

   mariadb:
     container_name: mariadb
     image: mariadb:latest
     restart: always
     volumes:
      - ./mariadb/init.sql:/docker-entrypoint-initdb.d/init.sql
      - ./mariadb/init_data:/docker-entrypoint-initdb.d/init_data
     ports:
       - 8084:3306
     environment:
       MYSQL_ROOT_PASSWORD: admin
       MYSQL_DATABASE: mydb
       MYSQL_USER: user
       MYSQL_PASSWORD: user
