version: "3.4"

services:
  bike-brain:
    container_name: bike-brain
    build:
      context: .
      dockerfile: ./Dockerfile.bike
    working_dir: /brain/app
    command: python3 main.py
    networks:
      - vteam_default
