version: "3.4"

services:
  bike-brain:
    container_name: bike-brain
    build:
      context: .
      dockerfile: ./Dockerfile.bike
    depends_on:
      - "server"
    working_dir: /brain/app
    command: python3 main.py

  server:
    container_name: server
    build:
      context: .
      dockerfile: ./Dockerfile.server
    working_dir: /server/app
    command: node server.js
    ports:
      - 5000:3000
    restart: on-failure
